### ISSUE TITLE
Replace inetutils-ping with iputils-ping

### ISSUE THREAD

**Issue by diederikdehaas** [tianon/docker-brew-debian#17]
Reasons:
1. iputils-ping has priority important, while inetutils-ping has priority extra, thus it would make more sense to include the former package;
2. When installing all packages with priority important (`aptitude install ~pimportant`, optionally without-recommends) you actually get the suggestion to remove the inetutils-ping package.

Having some more packages with priority important, like `net-tools` (ifconfig) and an editor, would be nice too, but I guess that should be a separate issue.

**Comment by tianon** [comment]
@paultag what're your thoughts on removing both `ping` and `ip` from the base image?  Looking back since my last comment more than a year ago, I think I've come around to it seeming a little dangerous to remove them now, given that they're used _so_ often in container startup scripts to verify connectivity or scrape IP address information.

**Comment by sathieu** [comment]
maybe remove them from stretch and sid? Or maybe sid only, and then buster.

**Comment by paultag** [comment]
Yeah. Seems like it'll break a bunch of things. Maybe start on the slim variant and see how that goes?

**Comment by tianon** [comment]
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:

(Which includes this improvement for the `slim` variants! :+1:  -- see the output of `apt-mark showmanual` :sunglasses:)
