### ISSUE TITLE
systemd bloat in jessie image

### ISSUE THREAD

**Issue by accursoft** [tianon/docker-brew-debian#19]
The jessie image is ~50% bigger than wheezy. systemd appears to be a major culprit, with `lib/systemd` and `lib/udev` adding about 20Mb.

Does a docker image really need a heavy-weight init system? Is it possible to build the image with a stripped-down systemd?

**Comment by tianon** [comment]
It's likely possible to get systemd to not be part of the image, but then
we're moving further away from an upstream-supported configuration.  This
image is created from the "minbase" variant in a standard debootstrap,
which is defined as the absolute minimum set of packages for a functioning
Debian system.  If we start removing packages from that set, we may run
into some serious dependency resolution issues, since other packages are
not required to list explicitly their dependencies on packages in this
minimal set.

**Comment by accursoft** [comment]
I've implemented this suggestion and #18 in [accursoft/micro-jessie](https://registry.hub.docker.com/u/accursoft/micro-jessie/).
