### ISSUE TITLE
The name of Docker's official Image of Debian

### ISSUE THREAD

**Issue by kretcheu** [tianon/docker-brew-debian#29]
I think the name of image distributed by Docker-Hub of Debian it's not good. 
Docker published with name "official Debian" and this may confuse the users because
they possible think that project Debian made this image and it 's not true.

Suggestions of name:
- Image of Debian mantained by Docker
- Docker's image of Debian

**Comment by tianon** [comment]
This image is maintained by me and @paultag, both of whom are Debian
Developers.  It is not maintained by Docker, Inc.

**Comment by kretcheu** [comment]
Thanks for your work @tianon and @paultag but can I understand that this image is endorced by Debian project?

**Comment by turicas** [comment]
@tianon, I think @kretcheu is asking about officiality of this image because:

- [CreateDockerImage page on Debian Wiki](https://wiki.debian.org/Cloud/CreateDockerImage) says it is "semi-official";
- The [Docker page on Debian Wiki](https://wiki.debian.org/Docker) also says *official* in quotes; and
- The [*debian* repository on Docker Hub](https://hub.docker.com/_/debian/) does not explicitly say it is officially maintained by Docker Hub, not by Debian Project (actually the page looks to speak on behalf of Debian Project).

**Comment by paultag** [comment]
@kretcheu I understand you're well-meaning, but our trademark policy is very liberal in Debian. Why are you bringing this up? We have two project members (debian developers with @debian.org emails) maintaining the image, which is way more than you get elsewhere.

I see no reason to change this. If needed, I'll get the DPL to sign off on the image.
