### ISSUE TITLE
CVE-2015-7547: docker hub stretch image still vulnerable

### ISSUE THREAD

**Issue by diocles** [tianon/docker-brew-debian#35]
https://security-tracker.debian.org/tracker/CVE-2015-7547 says this was fixed in 2.21-8. But the latest debian:stretch image has 2.21-7:

```
tretout@thinkpad> docker pull debian:stretch                             ~
stretch: Pulling from library/debian
3fb103290e9b: Already exists 
a3ed95caeb02: Already exists 
Digest: sha256:29fa2b09e1cbe7a90858e39098f9e75b0e50819b1b290bb8b5a48d4848ed7877
Status: Image is up to date for debian:stretch
tretout@thinkpad> docker run --rm -it debian:stretch /bin/bash           ~
root@1db19ec42645:/# dpkg -l libc6
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libc6:amd64    2.21-7       amd64        GNU C Library: Shared libraries
```

**Comment by tianon** [comment]
Yes, at the time the images were generated, the package hadn't migrated to stretch yet -- if you're security sensitive, I'd actually recommend sticking to either stable (currently jessie) or sid/unstable, since updates to testing are usually subject to a delay (even for security updates) anywhere from 2 days to as many as 10 days (or more depending on bug statuses), and holding up all the other suite updates waiting for that wouldn't make sense so testing is usually going to be lagging.

That being said, I'll see about generating new stretch/testing rootfs tarballs later today.

**Comment by tianon** [comment]
See 15a046ef540d8956940fff853ef6c8c3feab8d0a and https://github.com/docker-library/official-images/issues/1475. :+1:
