### ISSUE TITLE
debian:x.y images are moving targets

### ISSUE THREAD

**Issue by paddy-hack** [tianon/docker-brew-debian#43]
I am trying to write `Dockerfile`'s that create images for use in _reproducible_ builds.  To that end I modify the `sources.list` so that it looks like

```
deb http://httpredir.debian.org/debian wheezy main
```

without any entries for updates, security or otherwise.  I accept the fact that Debian occasionally does a point release and adjust my `Dockerfile`s at my leisure.  I do the same for `jessie`, BTW.

The problem that I am facing is that the `debian:x.y` images appear to change over time.  I think this happens when there are security updates that affect packages in these images.  The security upgrade that bites me as of writing is the `libc6` one that came out after 7.9.  When the 7.9 image first came out, I had no trouble building an image `FROM debian:7.9` with my `Dockerfile`.  Now, that same `Dockerfile` fails to build an image because `libc6-dev` requires `libc6=2.13-38+deb7u9` (which implies downgrading from `2.13-38+deb7u10` as of writing).
Same thing when building `FROM debian:7.10` for that matter.

Personally, I would like to see the `:x.y` to be tags in the traditional VCS-sense, where tagged stuff does not change, _ever_.  I don't have any trouble with `:x`, `:wheezy` and `:oldstable` pointing to something more fleeting.
On the other hand, I also understand the desire to provide images that have all known security issues addressed.

However, this willy-nilly upgrading of the official images means that people building from the _same_ `Dockerfile` on different points in time do _not_ get the same image (assuming the build succeeds of course).  They would get something that depends on an official Debian base "image-du-jour".  I feel that flies in the face of what Docker promises.

I am not sure what the best way is to address this.  Maybe you could at least clarify that all images are rebuilt using the _same tag_ whenever there are security upgrades.  Another option would be to change current practice and "freeze" the `:x.y` builds (meaning they no longer get security upgrades).  Or maybe add a `:x.y-release` tag that doesn't get upgrades.  Perhaps even add a `:x.y-secure`?

Any thoughts or suggestions?

**Comment by sohrab-** [comment]
I use image digests, instead of tags, if I really want to ensure repeatability.

They are generated from crypto-hashing the image content so pulling an image using the digest should ensure you always pull the same one, regardless of tag.

From memory, Dockerfile format for it is `FROM <image name>@<image digest>`. Please consult the docs.

**Comment by tianon** [comment]
I definitely agree that if you're looking for exact "point in time" reproducibility, that image digests are what you're looking for.  https://github.com/docker-library/docs/blob/master/debian/tag-details.md is a good resource for discovering what the digest for a particular tag currently is, but it should also be relatively simple to `docker pull` the tag you're interested in and make note of the digest which is returned in the output.

Regarding building exact point release tarballs, I don't think there's an easy way that I could do so even if I wanted to -- `debootstrap` (and the archive mirrors) don't allow for that, to my knowledge. :disappointed:

**Comment by paddy-hack** [comment]
@sohrab Thanks for the suggestion of using digests.  I'll have a look.

@tianon The Debian `stable` (and `oldstable`) archives do not change until the next point release.  It is the use of the `stable/updates` and `stable-updates` that wreck the havoc that I've run into.  I have built my own Debian images with these two disabled in the past.  I'll see if I can dig up how I did that.

**Comment by paddy-hack** [comment]
Doh, that turned out to be pretty trivial!  After a
```shell
debootstrap --variant=minbase --components=main jessie /chroot http://httpredir.debian.org/debian
```
all that's in `/etc/apt/sources.list` is
```
deb http://httpredir.debian.org/debian jessie main
```
No entries for any updates, so unless they transition to `stable`, i.e. when there's a new point release, they won't get in.

**Comment by paddy-hack** [comment]
@sohrab- `FROM <image>@sha256:<digest>` works like a charm.

@tianon I have used `debian@sha256:a8aeae7c...`, i.e. the first `debian:7.10` build, but still run into the same `libc` problem.  I've been poking around a bit and found that [DSA-3480](https://www.debian.org/security/2016/dsa-3480) first introduces the version that is in the Docker image.  This version was released well before 7.10 came out.  However, is *not* part of the [7.10 point release](https://lists.debian.org/debian-announce/2016/msg00003.html).

Now, if the `debian:x.y` is to include all security upgrades "no matter what" that's fine, but please document it (and I'll go build my own `debian:x.y` images without these upgrades).  On the other hand, you might consider building images *without* any security upgrades, let's call them `debian:x.y-pristine`, and build the regular "security upgraded" `debian:x.y` images so that they derive `FROM debian-x.y-pristine`.

BTW, I also had a look at `contrib/mkimage/debootstrap`.  You can set the `DONT_TOUCH_SOURCES_LIST` environment variable to a non-empty string to prevent adding the `*updates` to the `sources.list`.

BTW2, if the build really uses that `mkimage.sh` symlink to build the *official* Debian Docker images :frowning:, then I'll definitely start building my own.  A symlink to your local copy means there is *zero* accountability :worried:.  I guess you just forgot to update the README.md and remove the symlink :wink:.

**Comment by tianon** [comment]
I think "_zero_ accountability" is a bit harsher than where we're at, but you're right that it's more opaque than I'd like -- I do include the build logs at least (https://github.com/tianon/docker-brew-debian/blob/8072332b0dadf2f2590292c5e545bf0f9c2320e6/jessie/build.log), from which the exact commands that were executed can be seen.

I'm still on the fence about not updating the release artifacts to include security updates -- I'd honestly be more inclined to simply remove the point release tags entirely, given that I don't see a lot of value in not having those security updates.  Can you elaborate a bit on the use case you've got that requires such a thing?

**Comment by paddy-hack** [comment]
Call me paranoid :wink: but I'd have to cull the commands from that log and adjust them to my system just in order to see if that really produces the image that I download (if I were so inclined).  It'd be so much easier if that symlink got replaced with whatever it is pointing at.

About the _zero_ accountability, yes, that is a bit harsh perhaps.  Let's say there is next to no reproducibility.  Which, conveniently, connects to my use case: reproducible builds of *my* images and reproducible CI builds using *my* images.  The images are meant for C/C++ software development, not providing some internet facing (micro)service.  I care more about CI build reproducibility of all of the project's development branches for all developers than security.  

Debian is a decent fit for this because its security and other upgrades are kept out of the stable repositories (until the next point upgrade).  I can give someone my Dockerfile and they can rebuild the same image themselves (until Debian's next point upgrade) as long as your Debian base images don't move the *x.y* tags **and** do not include any security upgrades that may prevent my Dockerfiles from installing additional packages (like in the `libc-dev` case for `wheezy`).

Using SHA256 digests works around the moving *x.y* tags but are completely unintelligible to humans so I have to resort to putting in comments explaining what *x.y* the digest corresponds to.  The security upgrades that get included is not something that can be worked around easily.  The only way that I can think of is downgrading in my Dockerfile :scream:.

The *x.y* tags *are* nice to have around.  Debian announces its point releases so it helps to know that there is an *official* Docker image for it.  Please note that security and important upgrades are merged to stable with every point release.  Now, if you include security upgrades released after the *x.y* point release announcement, the Docker image isn't really Debian *x.y* anymore.  It's *x.y* + security upgrades and in some cases that can cause a headache if someone like myself does not want to use the security archives.

Like I mentioned in my previous comment, you can turn off inclusion of the security archives quite easily to build `debian:x.y-pristine` and then build the same kind of `debian:x.y` images as now
```
FROM debian:x.y-pristine
```
by activating the security archive, and an apt-get update and install, followed by suitable cleanup.

If you don't like that, that's fine but at least please mention that the *x.y* "tag" is a moving target; **not** a tag in the VCS sense but more like the `HEAD` of a particular branch.

Yes, you can move VCS tags with some VCSs but that's an anti-pattern (like rebasing published `git` branches).  It's a bit unfortunate that Docker overloads the word "tag" in a way that is similar but not the same as it has been using in VCS circles for ages.

Hmm, I think I elaborated a bit too much maybe :smiley:

**Comment by colinmollenhour** [comment]
I came looking for this type of discussion because I want to make sure there is a way to stay up-to-date with security updates so am on the opposite side of the fence than @paddy-hack but can still appreciate his issue and would like to see a good solution. It appears based on my latest builds that some security patches are actually not present in the current build so I don't know if this is because the security repo is not being included or if it was just built before the security patch was released and hasn't been rebuilt since..

Example: https://security-tracker.debian.org/tracker/DSA-3773-1
These three CVE's were [fixed in security](https://tracker.debian.org/media/packages/o/openssl/changelog-1.0.1t-1%2Bdeb8u6) on January 26 so almost a week ago.

So if "security" is already used in the build, how do you determine when to do new builds?

It looks like for Ubuntu you are already tagging releases with build dates which I like. This way for people who want stability they can use a dated tag like "debian:jessie-2017-02-01" and for people that want security over stability they could use "debian:jessie". Any reason not to do this for Debian like you are for Ubuntu?

Thanks!

**Comment by yosifkit** [comment]
@colinmollenhour The fixed CVE's you mention are not applicable to the Debian image, since it does not include `openssl`.  If there are actionable important CVE's in the images, we often create an issue like https://github.com/docker-library/official-images/issues/1691 to track them.  You'll notice that even though openssl is not in the image we included Debian in that list so that by generating a new tarball and resulting image we would cause all downstream images to need a rebuild which would then allow those that install openssl to get the latest version.  If there is not a pressing CVE, we still try to update the Debian and Ubuntu images at least once a month (and for releases like Debian 8.7).

The dates on the Ubuntu images are based on the date that the tarball was created by Canonical in https://partner-images.canonical.com/core/ and may not always reflect the build date of the image since it could've been built a few days later.

If a user wants a "point-in-time" specific image, they should be using the sha256 to pull the image.  We keep a history of those over here: https://github.com/docker-library/repo-info/tree/master/repos/debian/remote.  Even still, using a specific Debian image and installing things through apt may not produce the same image 6 months later.  Even if you pin every package to a version number, they may become unavailable.

**Comment by colinmollenhour** [comment]
Thanks for the info @yosifkit. I might just add an `apt-get upgrade` in my own builds then even though the layers would be bigger than necessary..

**Comment by tianon** [comment]
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:
