### ISSUE TITLE
couchdb cannot be installed

### ISSUE THREAD

**Issue by sscherfke** [tianon/docker-brew-debian#61]
The package `couchdb` cannot be installed in debian:sid:
```bash
$ sudo docker run --rm -it debian:sid bash
root@25727b6fccd7:/# apt-get update && apt-get install couchdb
...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 couchdb : Depends: libicu52 (>= 52~m1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by ederrm** [comment]
run apt-get update before use apt-get install

**Comment by ederrm** [comment]
$ docker run --rm -it debian:sid bash
root@7f732d0096e9:/# echo "deb http://deb.debian.org/debian stable main" > /etc/apt/sources.list.d/debian-stable.list
root@7f732d0096e9:/# apt-get update && apt-get install -qy couchdb

**Comment by tianon** [comment]
Normally I'd expect an error like that in Sid to mean that `couchdb` is part of a transition (https://release.debian.org/transitions/), but I can't see any that include it (the `auto-icu` tracker doesn't mention `couchdb`).  I'd also check https://buildd.debian.org/status/package.php?p=couchdb, but it looks like `couchdb` hasn't been rebuilt for a while.

Given that, I imagine it was probably removed from Stretch specifically due to whatever is causing this (since AFAICT, it's only in Sid and Wheezy currently).

**Comment by tianon** [comment]
See also https://bugs.debian.org/746053 for why it hasn't been rebuilt recently (`couchdb: FTBFS: configure: error: The installed Erlang version must be >= R14B (erts-5.8.1) and <R17 (erts-5.11)`).

**Comment by tianon** [comment]
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:
