### ISSUE TITLE
Errors installing packages due to unexistent man pages directory

### ISSUE THREAD

**Issue by nghiant2710** [tianon/docker-brew-debian#65]
```
[Build]    aspell-autobuildhash: processing: en [en_US-wo_accents-only].
[Build]    Processing triggers for ca-certificates (20141019+deb8u2) ...
[Build]    Updating certificates in /etc/ssl/certs... 0 added, 0 removed; done.
[Build]    Running hooks in /etc/ca-certificates/update.d....
[Build]    done.
[Build]    done.
[Build]    Processing triggers for menu (2.1.47) ...
[Build]    Errors were encountered while processing:
[Build]     openjdk-7-jre-headless:amd64
[Build]     openjdk-7-jre:amd64
[Build]     default-jre
[Build]     arduino
[Build]    E: Sub-process /usr/bin/dpkg returned an error code (1)
[Build]    Removing intermediate container f6f6f937a059
[Error] Build failed: The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends xorg mono-complete libasound2-dev fluxbox dbus arduino g++ gcc usbutils make && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

And the root cause is:

```
[Build] update-alternatives: error: error creating symbolic link `/usr/share/man/man1/rmid.1.gz.dpkg-tmp': No such file or directory
```

The `/usr/share/man/man1` directory doesn't exist, and simply doing `mkdir /usr/share/man/man1` before installing OpenJDK fixes the issue.

I think this is a breaking issue, and an empty man directory should be created.

**Comment by yosifkit** [comment]
If you are using one of the debian slim images, the point of the image is to not include man pages and other documentation. I'm not sure why the openjdk package is still trying to do stuff in `/usr/share/man`.

@tianon would this be something to fix in the slim image or a bug to file on the openjdk package in Debian?

**Comment by tianon** [comment]
This is a "bug" in the slim images (or a feature, depending on how you look at it).  `update-alternatives` includes logic to ignore alternatives requests if the source file does not exist, but not the target file (so this is technically a "bug" in `update-alternatives`).  If you create the directory, `update-alternatives` will instead throw a warning about the source file not existing and carry on.

IMO, this "bug" is actually useful behavior since it makes clear that _something_ is trying to write to those purged directories, and serves as a reminder that extra care should be taken to ensure the package does not actually write anything meaningful there.

Also, this repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:

**Comment by yosifkit** [comment]
For future reference, this same issue is tracked in https://github.com/debuerreotype/debuerreotype/issues/10.
