### ISSUE TITLE
Debian jessie image on Docker hub contains known vulnerabilities

### ISSUE THREAD

**Issue by IPv4v6** [tianon/docker-brew-debian#66]
The latest jessie image contains vulnerabilities.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862806

Image:
```
"Id": "sha256:3e83c23dba6a16cd936a3dc044df71b26706c5a4c28181bc3ca4a4af9f5f38ee"
debian@sha256:476959f29a17423a24a17716e058352ff6fbf13d8389e4a561c8ccc758245937
"Created": "2017-05-08T23:28:15.327579341Z"
```

```
# apt-cache policy login
login:
  Installed: 1:4.2-3+deb8u3
  Candidate: 1:4.2-3+deb8u4
  Version table:
     1:4.2-3+deb8u4 0
        500 http://security.debian.org/ jessie/updates/main amd64 Packages
 *** 1:4.2-3+deb8u3 0
        500 http://deb.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
```

Please update the image.

**Comment by yosifkit** [comment]
Looks like the last Debian image rebuild was https://github.com/docker-library/official-images/pull/2931 and we usually stick to a roughly monthly rebuild schedule, so it would probably be scheduled for next week anyway.  I see that the update you mention is https://packages.qa.debian.org/s/shadow/news/20170531T010213Z.html and is a "regression fix" to CVE-2017-2616 (see also [debian security tracker](https://security-tracker.debian.org/tracker/CVE-2017-2616)).

This looks to be specifically about the su binary, which we do not recommend for switching users in containers.  We instead recommend using `--user` on docker run/exec, or USER in a Dockerfile, or gosu for stepping down from root to another user at runtime (like the [redis image](https://github.com/docker-library/redis/blob/24aa66d88990e0eeec71bd39862744fdb7b862e4/3.2/docker-entrypoint.sh#L13)) since it doesn't stay resident and muck with signals like su does.

Since this involves being able to send sigkill to other processes and given that processes in the container are in a PID namespace, the attack surface is small enough that I don't think this warrants an immediate security rebuild of the image and can wait for a rebuild sometime next week.

**Comment by tianon** [comment]
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:
